const links={github:"https://github.com/AkramCodeer",linkedin:"https://www.linkedin.com/in/akram-khan-5a7a06201/",email:"mailto:akram1612khan@gmail.com"};
const skills=["JavaScript","React","Next.js","Node.js","Express","MongoDB","Angular","Firebase","REST APIs","Git & GitHub","OpenAI API","Generative AI","Speech-to-Text","Responsive UI"];
const Arrow=()=> <span aria-hidden="true">↗</span>;
export default function Home(){return <main>
  <header className="nav shell"><a className="mark" href="#home" aria-label="Homepage">AK<span>°</span></a><nav><a href="#work">Work</a><a href="#skills">Skills</a><a href="#connect">Connect</a></nav><a className="nav-cta" href={links.email}>Let&apos;s talk <Arrow/></a></header>
  <section className="hero shell" id="home"><div className="hero-copy"><p className="eyebrow"><i/> FULL STACK & AI DEVELOPER · INDIA</p><h1>I build web experiences that <em>move</em> people.</h1><p className="lede">A developer with an engineering foundation, creating clean interfaces, AI-powered tools, and dependable products from first idea to final interaction.</p><div className="hero-actions"><a className="button button-dark" href="#work">See selected work <Arrow/></a><a className="inline-link" href={links.linkedin} target="_blank" rel="noreferrer">Connect on LinkedIn <Arrow/></a></div></div><div className="hero-visual" aria-hidden="true"><div className="hero-ring"/><div className="hero-disc"><span>OPEN TO<br/>COLLABORATE<br/>· 2024 ·</span></div><div className="hero-chip">BUILD<br/>WITH<br/>PURPOSE</div><div className="hero-star">✦</div><p className="hero-caption">turning ambitious<br/>ideas into the web</p></div><p className="scroll-note">SCROLL TO EXPLORE <b/></p></section>
  <section className="intro shell"><p className="section-label">01 / WHAT DRIVES ME</p><div><p className="display-copy">I care about the details that make a product feel <em>effortless</em> — the ones users may never notice, but always <strong>feel.</strong></p><div className="numbers"><div><b>01</b><span>Engineering-led<br/>problem solving</span></div><div><b>02</b><span>AI-powered web<br/>experiences</span></div><div><b>03</b><span>Curiosity, always<br/>in progress</span></div></div></div></section>
  <section className="work" id="work"><div className="shell"><div className="section-top"><p className="section-label">02 / SELECTED WORK</p><div><h2>A few things I&apos;ve been <em>building.</em></h2><p>From live AI assistance to user-focused commerce experiences, I make software that responds to real needs.</p></div></div><div className="project-grid"><a className="project project-lime" href="https://github.com/AkramCodeer/ecoute" target="_blank" rel="noreferrer"><div className="browser"><div className="browser-bar"><i/><i/><i/></div><div className="dash"><aside/><div><span/><span/><span/><span/></div></div></div><div className="project-meta"><p>AI EXPERIENCE / 01 <Arrow/></p><h3>Écoute</h3><span>Live transcription · GPT-3.5 · JavaScript</span></div></a><a className="project project-peach" href="https://github.com/AkramCodeer/AniMates" target="_blank" rel="noreferrer"><div className="phone"><div className="notch"/><p>Shop<br/><em>smarter.</em></p><div className="phone-card"/><div className="phone-line"/></div><div className="project-meta"><p>WEB COMMERCE / 02 <Arrow/></p><h3>AniMates</h3><span>React · Cart · Wishlist · Payments</span></div></a></div><p className="project-note">Explore more projects, experiments, and source code on <a href={links.github} target="_blank" rel="noreferrer">github.com/AkramCodeer ↗</a></p></div></section>
  <section className="ai-section"><div className="shell ai-inner"><div><p className="section-label">03 / AI & GENERATIVE WORK</p><h2>Making AI feel<br/><em>useful, not noisy.</em></h2><p>I explore AI as a product capability: building interfaces that turn speech into text, use generative models to help people respond, and make complex tools feel approachable.</p><a className="button button-dark" href="https://github.com/AkramCodeer/ecoute" target="_blank" rel="noreferrer">View Écoute on GitHub <Arrow/></a></div><div className="ai-card"><div className="wave">{Array.from({length:12}).map((_,i)=><i key={i}/>)}</div><p>LIVE CONVERSATION</p><h3>Transcribe.<br/>Understand.<br/><em>Respond.</em></h3><span>GPT-3.5 SUGGESTED RESPONSE</span></div></div></section>
  <section className="skills shell" id="skills"><p className="section-label">04 / TOOLKIT</p><div><h2>Fluent in the <em>full</em> picture.</h2><p className="skills-lede">I work across the web stack, with a growing focus on AI-powered experiences and helpful automation.</p><div className="skill-cloud">{skills.map((skill,index)=><span key={skill} className={index===1||index===3||index===11?"accent":""}>{skill}</span>)}</div></div></section>
  <section className="connect" id="connect"><div className="shell connect-inner"><p className="section-label">05 / KEEP IN TOUCH</p><h2>Let&apos;s make something<br/><em>worth opening.</em></h2><p className="connect-copy">Looking for a collaborator, a developer, or simply want to share an idea? My inbox and social profiles are open.</p><div className="socials"><a href={links.linkedin} target="_blank" rel="noreferrer"><small>01</small> LinkedIn <Arrow/></a><a href={links.github} target="_blank" rel="noreferrer"><small>02</small> GitHub <Arrow/></a><a href={links.email}><small>03</small> Email me <Arrow/></a></div><footer><span>© 2024 Akram Khan</span><span>Made with focus & curiosity.</span><a href="#home">BACK TO TOP ↑</a></footer></div></section>
</main>}
